src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReclamationRepository::class)
 */
class Reclamation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $objet;

    /**
     * @ORM\Column(type="text")
     */
    private $motif;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateCreation;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reclamation")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $matiere;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $professeur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getObjet(): ?string
    {
        return $this->objet;
    }

    public function setObjet(string $objet): self
    {
        $this->objet = $objet;

        return $this;
    }

    public function getMotif(): ?string
    {
        return $this->motif;
    }

    public function setMotif(string $motif): self
    {
        $this->motif = $motif;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation=new \DateTime();
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getMatiere(): ?string
    {
        return $this->matiere;
    }

    public function setMatiere(string $matiere): self
    {
        $this->matiere = $matiere;

        return $this;
    }

    public function getProfesseur(): ?string
    {
        return $this->professeur;
    }

    public function setProfesseur(string $professeur): self
    {
        $this->professeur = $professeur;

        return $this;
    }
   

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Reclamation::class, mappedBy="user", orphanRemoval=true)
     */
    private $reclamation;

    public function __construct()
    {
        $this->reclamation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
       $roles[] = '';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Reclamation[]
     */
    public function getReclamation(): Collection
    {
        return $this->reclamation;
    }

    public function addReclamation(Reclamation $reclamation): self
    {
        if (!$this->reclamation->contains($reclamation)) {
            $this->reclamation[] = $reclamation;
            $reclamation->setUser($this);
        }

        return $this;
    }

    public function removeReclamation(Reclamation $reclamation): self
    {
        if ($this->reclamation->removeElement($reclamation)) {
            // set the owning side to null (unless already changed)
            if ($reclamation->getUser() === $this) {
                $reclamation->setUser(null);
            }
        }

        return $this;
    }
    public  function __toString()
    {
        return $this->getEmail();
    }
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
 

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('objet',TextType::class, [
                'attr' =>['class'=>'form-control','placeholder'=>'Objet de votre reclamation']
            ])
            ->add('motif',TextareaType::class , [
                'attr' =>['class'=>'form-control', 'placeholder'=>'motif']
                ])
            ->add('matiere',TextType::class , [
                'attr' =>['class'=>'form-control', 'placeholder'=>'Matiere']
                ])
            ->add('professeur',TextType::class , [
                'attr' =>['class'=>'form-control', 'placeholder'=>'Prof']
                ])
          
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Form\ReclamationType;
use App\Repository\ReclamationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/reclamation")
 * 
 */
class ReclamationController extends AbstractController 
{
    
    /**
     * @Route("/", name="reclamation_index", methods={"GET"})
     * 
     */
    public function index(ReclamationRepository $reclamationRepository): Response
    {
        if ($this->getUser()->getRoles()[0]=="ROLE_ADMIN"){

            return $this->render('reclamation/index.html.twig', [
                'reclamations' => $reclamationRepository->findAll(),
            ]);
        }
        else{
            return $this->redirectToRoute('reclamation_indexEtud');

        }

    }
      /**
     * @Route("/indexEtud", name="reclamation_indexEtud", methods={"GET"})
     * 
     */
    public function indexEtud(ReclamationRepository $reclamationRepository): Response
    {
       
            return $this->render('reclamation/index.html.twig', [
                'reclamations' => $reclamationRepository->findByUser($this->getUser()),
            ]);
      

    }



    //   /**
    //  * @Route("/confirmation", name="reclamation_confirmation")
    //  * @IsGranted("ROLE_USER")
    //  */
    // public function confirmation(): Response
    // {
    //     $reclamation=$this->getUser()->getReclamation();
       
    //      $message="Réclamation envoyé avec succes !";
    //     return $this->render('reclamation/confirmation.html.twig',[
    //         'message' =>$message,
    //         'reclamation'=>$reclamation
    //     ]);
    // }


    /**
     * @Route("/new", name="reclamation_new", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     * 
     */
    public function new(Request $request): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);
        $message="Réclamation envoyé avec succes !";

        if ($form->isSubmitted() && $form->isValid()) {

                $reclamation->setUser($this->getUser());

                $reclamation->setDateCreation($reclamation->getDateCreation());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reclamation);
            $entityManager->flush();
           // confirmation($reclamation);

         //   return $this->redirectToRoute('reclamation_confirmation');
         return $this->render('reclamation/confirmation.html.twig', [
            'reclamation' => $reclamation,
            'message' =>$message,

        ]);
        }

        return $this->render('reclamation/new.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reclamation_show", methods={"GET"})
     * @IsGranted("ROLE_USER")
     */
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reclamation_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     */
    public function edit(Request $request, Reclamation $reclamation): Response
    {
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reclamation_index');
        }

        return $this->render('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reclamation_delete", methods={"DELETE"})
     * @IsGranted("ROLE_USER")
     */
    public function delete(Request $request, Reclamation $reclamation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reclamation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reclamation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reclamation_index');
    }

    
  
}

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reclamation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
   <br> <button class="btn btn-lg btn-success">{{ button_label|default('Envoyer') }}</button>
{{ form_end(form) }}

templates/reclamation/confirmation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Confirmation!{% endblock %}

{% block body %}


    <br><br> <br><div class="jumbotron" align="center">
         <h1 class="display-4">{{message}}   </h1> 
        <hr class="my-4">
        <p class="lead">
            <a class="btn btn-primary btn-xlg" role="button" href="{{ path('app_logout') }}">Deconnexion</a>
            
            <a class="btn btn-primary btn-xlg" role="button" href="{{ path('reclamation_show', {'id': reclamation.id}) }}">Voir</a>
            <a class="btn btn-primary btn-xlg" role="button"  href="{{ path('reclamation_edit', {'id': reclamation.id}) }}">Modifier</a>
    
            <a class="btn btn-primary btn-xlg" role="button" href="{{ path('reclamation_new') }}">Refaire une réclamtion</a>

        </p>
        </div>
    </div> 
{% endblock %}

templates/reclamation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reclamation{% endblock %}

{% block body %}
    <h1>Edit Reclamation</h1>

    {{ include('reclamation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reclamation_index') }}">back to list</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}

templates/reclamation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reclamation index{% endblock %}

{% block body %}
     {% if app.user %}
        <div class="mb-3">
            Vous vous connectés en temps que {{ app.user.username }}, <a href="{{ path('app_logout') }}">Deconnexion</a>
        </div>
    {% endif %}
    <table><h1 align='center'>Liste des réclamations</h1></table><br>

    <table  class=" table-striped table-bordered table-sm">
        <thead>
            <tr>
                <th>Id</th>
                <th>Objet</th>
                <th>Motif</th>
                <th>Matiere</th>
                <th>Prof</th>
                <th>DateCreation</th>
                {% if is_granted('ROLE_ADMIN')%}
                <th>Etudiant</th>
                 {% endif %}
                <th>actions</th>
                
            </tr>
        </thead>
        <tbody>
        {% for reclamation in reclamations %}
            <tr>
                <td>{{ reclamation.id }}</td>
                <td>{{ reclamation.objet }}</td>
                <td>{{ reclamation.motif }}</td>
                 <td>{{ reclamation.matiere }}</td>
                <td>{{ reclamation.professeur }}</td>
                
                <td>{{  reclamation.dateCreation|date('Y-m-d-H:m') }}</td>
                 {% if is_granted('ROLE_ADMIN')%}
                  <td>{{reclamation.user.email}}</td>
                 {% endif %}
                <td>
                    <a href="{{ path('reclamation_show', {'id': reclamation.id}) }}">voir</a>
                    {% if is_granted('ROLE_USER')%}
                          <a href="{{ path('reclamation_edit', {'id': reclamation.id}) }}">modifier</a>
                    {% endif %}
                </td>
                
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_USER')%}
         <br><br> <a class="btn btn-primary btn-lg btn-block" role="button" align="center"href="{{ path('reclamation_new') }}">Faire une réclamaton</a>
    {% endif %} 
{% endblock %}

templates/reclamation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Réclamation{% endblock %}

{% block body %}
 {% if app.user %}
        <div class="mb-3">
            Vous vous connectés en temps que {{ app.user.username }}, <a href="{{ path('app_logout') }}">Deconnexion</a>
        </div>
 {% endif %}
<div class="container"align="center">

<table class="table table-bordered"  >


<div class="card border-success mb-3" style="max-width: 100rem;">
  <div class="card-header"> <h2> Faire une nouvelle réclamation</h2></div><br>
  <div class="card-body">
    {{ include('reclamation/_form.html.twig') }}
  </div>
</div>
  

    

     {# <a href="{{ path('reclamation_confirmation', {'id': reclamation.id}) }}"></a> #}
  {#<a href="{{ path('reclamation_confirmation'), {'id': reclamation.id})  }}">truc</a>#}
</table>
</div>

{% endblock %}

templates/reclamation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reclamation{% endblock %}

{% block body %}
    <h1>Reclamation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reclamation.id }}</td>
            </tr>
            <tr>
                <th>Objet</th>
                <td>{{ reclamation.objet }}</td>
            </tr>
            <tr>
                <th>Motif</th>
                <td>{{ reclamation.motif }}</td>
            </tr>
            <tr>
                <th>DateCreation</th>
                <td>{{ reclamation.dateCreation ? reclamation.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reclamation_index') }}">back to list</a>

    <a href="{{ path('reclamation_edit', {'id': reclamation.id}) }}">edit</a>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}